[window]
decorations = "None"
dynamic_title = true
opacity = 1.0

[scrolling]
history = 10000

# Font configuration
[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 13.0

[cursor]
style = "Block"

[general]
import = ["~/.config/alacritty/themes/carbonfox.toml"]
working_directory = "/home/gak"

[keyboard]
bindings = [
    { key = "T", mods = "Control", action = "CreateNewWindow" }
]
